### ISSUE TITLE
Website no longer working

### ISSUE THREAD

**Issue by owen-the-kid** [Jupiee/open-lychee-api#1]
https://lychee-engine.xyz/ has stopped working and just shows a for sale page, has the host name changed?

**Comment by Jupiee** [comment]
hey, [https://lychee-engine.xyz/ ](https://lychee-engine.xyz/) domain is expired, use the default permanent cloudflare domain [https://lychee-engine.pages.dev/](https://lychee-engine.pages.dev/)

**Comment by owen-the-kid** [comment]
thanks
